import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:yeong_twitter/constants/gaps.dart';
import 'package:yeong_twitter/constants/sizes.dart';
import 'package:yeong_twitter/constants/text.dart';
import 'package:yeong_twitter/features/authentication/a_whats_happening_screen.dart';
import 'package:yeong_twitter/features/onboarding/widgets/next_button.dart';

const interests = [
  "Fashion & beauty",
  "Outdoors",
  "Arts & culture",
  "Animation & comics",
  "Business & finance",
  "Food",
  "Travel",
  "Entertainment",
  "Music",
  "Gaming",
  "Family",
  "Fitness & Health",
  "Dance",
  "Home & Garden",
  "Daily Life",
  "Comedy",
  "Animals",
  "Learning",
  "Sports",
];

const interestDetails = [
  [
    "Fashion",
    "Beauty",
    "Makeup",
    "Hairstyles",
    "Skincare",
    "Street style",
    "Runway shows",
    "Fashion week",
    "Designer brands",
    "Luxury fashion",
    "Sustainable fashion",
    "OOTD",
    "Personal style",
    "Men's fashion",
    "Women's fashion",
    "Unisex fashion",
    "Accessories",
    "Jewelry",
    "Bags",
    "Shoes",
    "Perfumes",
    "Beauty tips",
    "Makeup tutorials",
    "Hair care",
    "Nail art",
    "Celebrity style",
    "Red carpet looks",
    "Fashion magazines",
    "Fashion photography",
    "Modeling",
    "Body care",
    "Beauty products",
    "Cosmetic brands",
    "Vegan beauty",
    "K-beauty",
  ],
  [
    "Camping",
    "Hiking",
    "Backpacking",
    "Trekking",
    "Rock climbing",
    "Bouldering",
    "Trail running",
    "Fishing",
    "Hunting",
    "Kayaking",
    "Canoeing",
    "Rafting",
    "Surfing",
    "Paddleboarding",
    "Sailing",
    "Snorkeling",
    "Scuba diving",
    "Wildlife watching",
    "Birdwatching",
    "Nature photography",
    "Stargazing",
    "Outdoor cooking",
    "BBQ",
    "Picnics",
    "Cycling",
    "Mountain biking",
    "Snowboarding",
    "Skiing",
    "Snowshoeing",
    "Cross-country skiing",
    "Trail maps",
    "Outdoor gear",
    "Adventure travel",
    "Survival skills",
    "Bushcraft",
    "Eco-tourism",
  ],
  [
    "Fine art",
    "Painting",
    "Sculpture",
    "Photography",
    "Illustration",
    "Digital art",
    "Street art",
    "Graffiti",
    "Art exhibitions",
    "Museums",
    "Galleries",
    "Art history",
    "Cultural heritage",
    "Architecture",
    "Design",
    "Calligraphy",
    "Pottery",
    "Crafts",
    "Handmade goods",
    "Traditional art",
    "Performance art",
    "Opera",
    "Ballet",
    "Contemporary dance",
    "Literature",
    "Poetry",
    "Storytelling",
    "Film as art",
    "Art festivals",
    "Cultural festivals",
    "World heritage sites",
    "Cultural preservation",
    "Art criticism",
    "Art education",
  ],
  [
    "Animation",
    "2D animation",
    "3D animation",
    "Stop motion",
    "Anime",
    "Manga",
    "Webtoons",
    "Cartoons",
    "Comic books",
    "Graphic novels",
    "Storyboard art",
    "Character design",
    "Voice acting",
    "Pixar",
    "Disney animation",
    "Anime conventions",
    "Cosplay",
    "Fan art",
    "Superheroes",
    "Marvel comics",
    "DC comics",
    "Manga adaptations",
    "Light novels",
    "Animated series",
    "Short animations",
    "Opening themes",
    "Ending themes",
    "Crossover events",
    "Comic strip",
    "Illustration",
    "Fan fiction",
    "Chibi art",
    "Doujinshi",
    "Visual novels",
  ],
  [
    "Entrepreneurship",
    "Startups",
    "Small business",
    "Corporate strategy",
    "Business management",
    "E-commerce",
    "Retail",
    "Marketing",
    "Digital marketing",
    "Branding",
    "Advertising",
    "Public relations",
    "Investment",
    "Stock market",
    "Mutual funds",
    "ETFs",
    "Venture capital",
    "Private equity",
    "Angel investors",
    "Financial planning",
    "Personal finance",
    "Budgeting",
    "Credit scores",
    "Loans",
    "Real estate",
    "Wealth management",
    "Taxes",
    "Accounting",
    "Mergers & acquisitions",
    "Business law",
    "International trade",
    "Economics",
    "Cryptocurrency",
    "Blockchain",
    "Fintech",
    "Economic policy",
  ],
  [
    "Cuisine",
    "Recipes",
    "Cooking",
    "Baking",
    "Grilling",
    "Vegan food",
    "Vegetarian food",
    "Street food",
    "Fast food",
    "Fine dining",
    "Casual dining",
    "Desserts",
    "Pastries",
    "Bread",
    "Seafood",
    "Meat dishes",
    "Pasta",
    "Pizza",
    "Sushi",
    "Noodles",
    "Salads",
    "Soups",
    "Appetizers",
    "Snacks",
    "Food photography",
    "Food styling",
    "Cooking tips",
    "Food festivals",
    "Local delicacies",
    "Street markets",
    "Fermented foods",
    "Spices & herbs",
    "Beverages",
  ],
  [
    "Adventure travel",
    "Solo travel",
    "Group travel",
    "Backpacking",
    "Luxury travel",
    "Budget travel",
    "Road trips",
    "Train travel",
    "Cultural travel",
    "Eco-tourism",
    "Sustainable travel",
    "Beach vacations",
    "Mountain escapes",
    "Island hopping",
    "Historical sites",
    "World heritage sites",
    "National parks",
    "Wildlife safaris",
    "Travel photography",
    "Travel tips",
    "Itineraries",
    "Travel blogs",
    "Travel vlogs",
    "Hotels",
    "Hostels",
    "Airbnb",
    "Camping trips",
    "Glamping",
    "Packing tips",
    "Visa requirements",
    "Cultural etiquette",
  ],
  [
    "Anime",
    "Movies & TV",
    "Harry Potter",
    "Marvel Universe",
    "Movie news",
    "Naruto",
    "Movies",
    "Grammy Awards",
    "Entertainment",
    "Hollywood",
    "Bollywood",
    "K-drama",
    "Netflix",
    "Disney",
    "Pixar",
    "DC Universe",
    "Star Wars",
    "Game of Thrones",
    "Lord of the Rings",
    "Action movies",
    "Romantic comedies",
    "Documentaries",
    "Reality TV",
    "Award shows",
    "Academy Awards",
    "Golden Globe Awards",
    "Cannes Film Festival",
    "Film reviews",
    "Celebrity news",
    "Red carpet",
    "Voice acting",
    "Cartoons",
    "Comic books",
    "Theater & musicals",
    "Soundtracks",
    "Movie trailers",
  ],
  [
    "Rap",
    "R&B & soul",
    "Grammy Awards",
    "Pop",
    "K-pop",
    "Music industry",
    "EDM",
    "Music news",
    "Hip hop",
    "Reggae",
    "Rock",
    "Jazz",
    "Blues",
    "Classical",
    "Indie music",
    "Alternative",
    "Folk",
    "Metal",
    "Punk",
    "Country",
    "Gospel",
    "Soundtracks",
    "Live concerts",
    "Music festivals",
    "Billboard charts",
    "Songwriting",
    "Music production",
    "DJing",
    "Vinyl records",
    "Music awards",
    "World music",
    "Afrobeat",
    "Lo-fi",
    "Acoustic",
  ],
  [
    "Video games",
    "PC gaming",
    "Console gaming",
    "Mobile gaming",
    "Cloud gaming",
    "VR gaming",
    "AR gaming",
    "Esports",
    "Competitive gaming",
    "MMORPG",
    "FPS games",
    "RPG games",
    "Action-adventure games",
    "Simulation games",
    "Strategy games",
    "Indie games",
    "Retro games",
    "Game development",
    "Game design",
    "Game streaming",
    "Twitch",
    "YouTube Gaming",
    "Speedrunning",
    "Gaming news",
    "Game reviews",
    "Early access games",
    "Beta testing",
    "Cosplay",
    "Gaming merchandise",
    "Board games",
    "Card games",
    "Tabletop RPG",
  ],
  [
    "Parenting",
    "Pregnancy",
    "Newborn care",
    "Child development",
    "Education for kids",
    "Homeschooling",
    "Family travel",
    "Family meals",
    "Family traditions",
    "Child safety",
    "Playtime",
    "Outdoor play",
    "Family health",
    "Mental health for parents",
    "Marriage",
    "Relationships",
    "Adoption",
    "Family events",
    "Family gatherings",
    "Sibling relationships",
    "Pet care",
    "Home organization",
    "Chores for kids",
    "Allowance & money lessons",
    "Storytime",
    "After-school activities",
    "Parent support groups",
    "Emergency preparedness",
    "Digital parenting",
  ],
  [
    "Exercise",
    "Workouts",
    "Strength training",
    "Cardio",
    "Yoga",
    "Pilates",
    "Stretching",
    "CrossFit",
    "HIIT",
    "Running",
    "Cycling",
    "Swimming",
    "Martial arts",
    "Dance fitness",
    "Home workouts",
    "Gym workouts",
    "Personal training",
    "Sports",
    "Healthy eating",
    "Nutrition",
    "Meal planning",
    "Weight loss",
    "Muscle gain",
    "Mental health",
    "Mindfulness",
    "Meditation",
    "Stress management",
    "Sleep health",
    "Rehabilitation",
    "Healthy aging",
    "Public health",
    "Wellness retreats",
  ],
  [
    "Ballet",
    "Contemporary dance",
    "Jazz dance",
    "Hip hop dance",
    "Street dance",
    "Breakdancing",
    "Popping & locking",
    "Krump",
    "Tap dance",
    "Ballroom dance",
    "Latin dance",
    "Salsa",
    "Bachata",
    "Tango",
    "Cha-cha",
    "Rumba",
    "Swing dance",
    "Waltz",
    "K-pop dance",
    "Dance competitions",
    "Dance classes",
    "Dance tutorials",
    "Dance covers",
    "Dance festivals",
    "Cultural dances",
    "Folk dances",
    "Traditional dances",
    "Belly dance",
    "Pole dance",
    "Aerial dance",
  ],
  [
    "Interior design",
    "Home decor",
    "DIY projects",
    "Furniture",
    "Lighting",
    "Home renovation",
    "Home improvement",
    "Smart home",
    "Home organization",
    "Storage solutions",
    "Cleaning tips",
    "Sustainable living",
    "Eco-friendly homes",
    "Houseplants",
    "Indoor gardening",
    "Outdoor gardening",
    "Vegetable gardening",
    "Herb gardening",
    "Flower gardening",
    "Landscaping",
    "Patio design",
    "Balcony decor",
    "Home maintenance",
    "Pest control",
    "Home safety",
    "Real estate",
    "Home staging",
    "Garden tools",
    "Water features",
    "Outdoor lighting",
    "Greenhouses",
  ],
  [
    "Morning routine",
    "Evening routine",
    "Time management",
    "Productivity",
    "Work-life balance",
    "Meal prep",
    "Grocery shopping",
    "Cooking at home",
    "House cleaning",
    "Laundry",
    "Errands",
    "Commuting",
    "Car maintenance",
    "Budgeting",
    "Bill payments",
    "Decluttering",
    "Self-care",
    "Hobbies",
    "Reading",
    "Journaling",
    "Pet care",
    "Gardening",
    "Exercise",
    "Socializing",
    "Volunteering",
    "Mindfulness",
    "Relaxation",
    "Entertainment",
    "Music",
    "Childcare",
    "Home maintenance",
    "Seasonal chores",
    "Clothing care",
  ],
  [
    "Stand-up comedy",
    "Sketch comedy",
    "Improv comedy",
    "Parody",
    "Satire",
    "Dark comedy",
    "Slapstick",
    "Romantic comedy",
    "Comedy movies",
    "Comedy TV shows",
    "Sitcoms",
    "Comedy festivals",
    "Comedians",
    "Jokes",
    "One-liners",
    "Funny stories",
    "Pranks",
    "Internet memes",
    "Animated comedy",
    "Political comedy",
    "Musical comedy",
    "Comedy clubs",
    "Sketch groups",
    "Improvised musicals",
    "Physical comedy",
    "Character comedy",
    "Surreal comedy",
    "Comedy awards",
    "Online skits",
  ],
  [
    "Wildlife",
    "Pets",
    "Endangered species",
    "Animal rescue",
    "Animal adoption",
    "Veterinary care",
    "Animal training",
    "Animal behavior",
    "Animal welfare",
    "Zoo",
    "Aquarium",
    "Safari",
    "Birdwatching",
    "Marine life",
    "Farm animals",
    "Mammals",
    "Birds",
    "Fish",
    "Animal photography",
    "Animal documentaries",
    "Pet food",
    "Pet accessories",
    "Dog breeds",
    "Cat breeds",
    "Horse riding",
    "Service animals",
    "Therapy animals",
    "Wildlife conservation",
    "Animal tracking",
    "Animal rights",
  ],
  [
    "Education",
    "Online learning",
    "E-learning platforms",
    "Blended learning",
    "Lifelong learning",
    "Self-study",
    "Distance learning",
    "Classroom learning",
    "Tutoring",
    "Language learning",
    "STEM education",
    "Arts education",
    "Music education",
    "Coding",
    "Data science",
    "Machine learning",
    "Public speaking",
    "Critical thinking",
    "Problem solving",
    "Creative thinking",
    "Study tips",
    "Note-taking",
    "Research skills",
    "Exam strategies",
    "Educational apps",
    "Workshops",
    "Seminars",
    "Webinars",
    "Career development",
  ],
  [
    "Team sports",
    "Individual sports",
    "Football",
    "Soccer",
    "Basketball",
    "Baseball",
    "Softball",
    "Volleyball",
    "Tennis",
    "Table tennis",
    "Badminton",
    "Cricket",
    "Rugby",
    "Hockey",
    "Field hockey",
    "Golf",
    "Track and field",
    "Running",
    "Marathons",
    "Swimming",
    "Diving",
    "Water polo",
    "Surfing",
    "Kayaking",
    "Cycling",
    "Skateboarding",
    "Snowboarding",
    "Skiing",
    "Wrestling",
    "Boxing",
    "Martial arts",
    "Judo",
    "Karate",
    "Taekwondo",
    "MMA",
    "Esports",
    "Sports training",
    "Olympic Games",
    "Paralympic Games",
  ],
];

class InterestsSecondScreen extends StatefulWidget {
  final List<int> selectedIndexes;
  const InterestsSecondScreen({super.key, required this.selectedIndexes});

  @override
  State<InterestsSecondScreen> createState() => _InterestsSecondScreenState();
}

class _InterestsSecondScreenState extends State<InterestsSecondScreen> {
  final ScrollController _scrollController = ScrollController();
  final Map<int, List<String>> _selectedDetails = {};
  int _itemLength = 0;
  bool _showTitle = false;

  void _onScroll() {
    if (_scrollController.offset > 100) {
      if (_showTitle) return;
      setState(() {
        _showTitle = true;
      });
    } else {
      if (!_showTitle) return;
      setState(() {
        _showTitle = false;
      });
    }
  }

  @override
  void initState() {
    super.initState();
    _scrollController.addListener(() {
      _onScroll();
    });
  }

  void _onDetailTap(int index, String detail) {
    if (_selectedDetails.containsKey(index) &&
        _selectedDetails[index]!.contains(detail)) {
      _selectedDetails[index]!.remove(detail);
      _itemLength--;
    } else {
      if (!_selectedDetails.containsKey(index)) {
        _selectedDetails[index] = [];
      }
      _selectedDetails[index]!.add(detail);
      _itemLength++;
    }
    setState(() {});
  }

  bool _isSelected(int index, String detail) {
    if (!_selectedDetails.containsKey(index)) return false;
    return _selectedDetails[index]!.contains(detail);
  }

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }

  void _onNextTap() {
    if (_itemLength < 3) return;
    Navigator.push(
      context,
      MaterialPageRoute(builder: (context) => WhatsHappeningScreen()),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: AnimatedSwitcher(
          duration: Duration(milliseconds: 300),
          child:
              _showTitle
                  ? TtitleLarge(
                    "Choose your interests",
                    color: Theme.of(context).primaryColor,
                  )
                  : FaIcon(FontAwesomeIcons.twitter),
        ),
      ),
      body: SafeArea(
        child: Scrollbar(
          controller: _scrollController,
          child: SingleChildScrollView(
            controller: _scrollController,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Padding(
                  padding: EdgeInsets.symmetric(horizontal: Sizes.d24),
                  child: Column(
                    children: [
                      Gaps.v20,
                      TtitleLarge(
                        "What do you want to see on Twitter?",
                        fontSize: Sizes.d36,
                        maxLines: 3,
                      ),
                      Gaps.v20,
                      Opacity(
                        opacity: 0.5,
                        child: TbodyLarge(
                          "Interests are used to personalize your experience and will be visible on your profile.",
                          maxLines: 5,
                        ),
                      ),
                      Gaps.v20,
                      Divider(color: Colors.grey.shade400, thickness: 0.5),
                    ],
                  ),
                ),
                for (var index in widget.selectedIndexes) ...[
                  Gaps.v20,
                  Padding(
                    padding: EdgeInsets.symmetric(horizontal: Sizes.d20),
                    child: TtitleLarge(interests[index]),
                  ),
                  Gaps.v28,
                  SingleChildScrollView(
                    scrollDirection: Axis.horizontal,
                    padding: EdgeInsets.symmetric(horizontal: Sizes.d20),
                    child: SizedBox(
                      width: Sizes.d100 * 20,
                      child: Wrap(
                        spacing: Sizes.d10,
                        runSpacing: Sizes.d10,
                        children: [
                          for (var detail in interestDetails[index]) ...[
                            GestureDetector(
                              onTap: () => _onDetailTap(index, detail),
                              child: AnimatedContainer(
                                duration: Duration(milliseconds: 200),
                                padding: EdgeInsets.symmetric(
                                  horizontal: Sizes.d20,
                                  vertical: Sizes.d16,
                                ),
                                decoration: BoxDecoration(
                                  color:
                                      _isSelected(index, detail)
                                          ? Theme.of(context).primaryColor
                                          : null,
                                  borderRadius: BorderRadius.circular(
                                    Sizes.d32,
                                  ),
                                  border: Border.all(
                                    color:
                                        _isSelected(index, detail)
                                            ? Theme.of(context).primaryColor
                                            : Colors.grey.shade300,
                                  ),
                                ),
                                child: AnimatedDefaultTextStyle(
                                  style: Theme.of(
                                    context,
                                  ).textTheme.titleSmall!.copyWith(
                                    color:
                                        _isSelected(index, detail)
                                            ? Colors.white
                                            : Colors.black,
                                  ),
                                  duration: Duration(milliseconds: 200),
                                  child: Text(detail),
                                ),
                              ),
                            ),
                          ],
                        ],
                      ),
                    ),
                  ),
                  Gaps.v20,
                  Divider(
                    color: Colors.grey.shade400,
                    thickness: 0.5,
                    indent: Sizes.d16,
                    endIndent: Sizes.d16,
                  ),
                ],
              ],
            ),
          ),
        ),
      ),
      bottomNavigationBar: BottomAppBar(
        elevation: 1,
        color: Colors.white,
        padding: EdgeInsets.symmetric(
          horizontal: Sizes.d32,
          vertical: Sizes.d10,
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.end,
          children: [NextButton(disabled: _itemLength < 3, onTap: _onNextTap)],
        ),
      ),
    );
  }
}
