import 'package:flutter/material.dart';
import 'package:yeong_twitter/constants/sizes.dart';

class Gaps {
  static const v1 = SizedBox(height: Sizes.d1);
  static const v2 = SizedBox(height: Sizes.d2);
  static const v3 = SizedBox(height: Sizes.d3);
  static const v4 = SizedBox(height: Sizes.d4);
  static const v5 = SizedBox(height: Sizes.d5);
  static const v6 = SizedBox(height: Sizes.d6);
  static const v7 = SizedBox(height: Sizes.d7);
  static const v8 = SizedBox(height: Sizes.d8);
  static const v9 = SizedBox(height: Sizes.d9);
  static const v10 = SizedBox(height: Sizes.d10);
  static const v11 = SizedBox(height: Sizes.d11);
  static const v12 = SizedBox(height: Sizes.d12);
  static const v14 = SizedBox(height: Sizes.d14);
  static const v16 = SizedBox(height: Sizes.d16);
  static const v18 = SizedBox(height: Sizes.d18);
  static const v20 = SizedBox(height: Sizes.d20);
  static const v24 = SizedBox(height: Sizes.d24);
  static const v28 = SizedBox(height: Sizes.d28);
  static const v32 = SizedBox(height: Sizes.d32);
  static const v36 = SizedBox(height: Sizes.d36);
  static const v40 = SizedBox(height: Sizes.d40);
  static const v44 = SizedBox(height: Sizes.d44);
  static const v48 = SizedBox(height: Sizes.d48);
  static const v52 = SizedBox(height: Sizes.d52);
  static const v56 = SizedBox(height: Sizes.d56);
  static const v60 = SizedBox(height: Sizes.d60);
  static const v64 = SizedBox(height: Sizes.d64);
  static const v72 = SizedBox(height: Sizes.d72);
  static const v80 = SizedBox(height: Sizes.d80);
  static const v96 = SizedBox(height: Sizes.d96);
  static const v100 = SizedBox(height: Sizes.d100);

  static const h1 = SizedBox(width: Sizes.d1);
  static const h2 = SizedBox(width: Sizes.d2);
  static const h3 = SizedBox(width: Sizes.d3);
  static const h4 = SizedBox(width: Sizes.d4);
  static const h5 = SizedBox(width: Sizes.d5);
  static const h6 = SizedBox(width: Sizes.d6);
  static const h7 = SizedBox(width: Sizes.d7);
  static const h8 = SizedBox(width: Sizes.d8);
  static const h9 = SizedBox(width: Sizes.d9);
  static const h10 = SizedBox(width: Sizes.d10);
  static const h11 = SizedBox(width: Sizes.d11);
  static const h12 = SizedBox(width: Sizes.d12);
  static const h14 = SizedBox(width: Sizes.d14);
  static const h16 = SizedBox(width: Sizes.d16);
  static const h18 = SizedBox(width: Sizes.d18);
  static const h20 = SizedBox(width: Sizes.d20);
  static const h24 = SizedBox(width: Sizes.d24);
  static const h28 = SizedBox(width: Sizes.d28);
  static const h32 = SizedBox(width: Sizes.d32);
  static const h36 = SizedBox(width: Sizes.d36);
  static const h40 = SizedBox(width: Sizes.d40);
  static const h44 = SizedBox(width: Sizes.d44);
  static const h48 = SizedBox(width: Sizes.d48);
  static const h52 = SizedBox(width: Sizes.d52);
  static const h56 = SizedBox(width: Sizes.d56);
  static const h60 = SizedBox(width: Sizes.d60);
  static const h64 = SizedBox(width: Sizes.d64);
  static const h72 = SizedBox(width: Sizes.d72);
  static const h80 = SizedBox(width: Sizes.d80);
  static const h96 = SizedBox(width: Sizes.d96);
  static const h100 = SizedBox(width: Sizes.d100);
}
